### PR TITLE
DPLY-40: Use DbSessionFactory and DbSession to bridge the Hibernate 3…

### PR DESCRIPTION
**Pull request by akushylun**
… vs. 4 differences

https://issues.openmrs.org/browse/DPLY-40

### CODE REVIEW

**Comment by dkayiwa** [comment]
@akushylun did you see the above travis failure?

**Comment by dkayiwa** [comment]
@akushylun are you still interested in finishing this up?

**Comment by akushylun** [comment]
@dkayiwa, I am interested in this task, but I can try to solve it only on the next week. 
If it is available, I will try to finish it up.

**Comment by dkayiwa** [comment]
@akushylun next week is fine. Thanks!

**Comment by akushylun** [comment]
Used DbSessionFactory and DbSession instead of the SessionFactory class.
https://issues.openmrs.org/browse/DPLY-40

After changing <require_version>1.11.3, 1.10.2 - 1.10.*, 1.9.9 - 1.9.*</require_version> in module's config.xml and using the 1.9.9 version of openmrs-api dependency in pom.xml, the test method api/src/test/java/org/openmrs/module/metadatadeploy/MetadataUtilsTest.java was broken. Fixed the problem by changing getLocation(String uuid), but I am not sure it is a right solution.

**Comment by dkayiwa** [comment]
@akushylun do you mind squashing the commits into one? Could you also reserve formatting changes for another pull request? 😊

**Comment by dkayiwa** [comment]
@akushylun are you still working on this?

**Comment by akushylun** [comment]
@dkayiwa thank you for your tips! I squashed commits and made formatting changes in my IDE, so next pull requests will suit Coding Conventions.

**Comment by dkayiwa** [comment]
@akushylun are you still working on this?

**Pull request closed without merging**
